// src/lib/ocrSentiment.ts
//
// OCR evidence analysis:
//
// 1. Suspicion score:
//    Deterministic, explainable keyword scoring.
//    The LLM NEVER controls the suspicion score.
//
// 2. Sentiment:
//    LLM-based sentiment analysis using the existing llmClient.
//    The LLM returns:
//      - positive / neutral / negative
//      - confidence
//      - emotions
//      - reasoning
//
// 3. Explanation:
//    The same LLM call also produces an investigator-facing explanation.
//
// If the LLM is unavailable, the evidence is still saved and a clearly
// marked fallback result is returned.

import {
  callLlmForJson,
  LlmError,
  SupportedModel,
  DEFAULT_MODEL,
} from "./llmClient.js";

import { riskToStatus, type RiskLevel } from "./riskStatus.js";

// ─── Suspicion keyword groups ───────────────────────────────────────────

export type SuspicionFactor =
  | "financialFraud"
  | "identityDocument"
  | "controlledSubstance"
  | "weapon"
  | "operationalSecurity"
  | "urgencyPressure"
  | "transactionCoordination";

export const SUSPICION_FACTOR_LABELS: Record<SuspicionFactor, string> = {
  financialFraud: "Financial fraud terminology",
  identityDocument: "Identity-document terminology",
  controlledSubstance: "Controlled-substance terminology",
  weapon: "Weapons terminology",
  operationalSecurity: "Operational-security / evasion language",
  urgencyPressure: "Urgency or pressure language",
  transactionCoordination: "Transaction-in-progress language",
};

export interface SuspicionSignal {
  label: string;
  value: number;
  factor: SuspicionFactor;
}

const SUSPICION_GROUPS: {
  factor: SuspicionFactor;
  pattern: RegExp;
  value: number;
}[] = [
  {
    factor: "financialFraud",
    pattern:
      /\b(cvv|fullz|dumps?|carding|paypal|western union|\bwu\b|bank ?log|swift|iban|\bbin\b|wire transfer|money mule|chargeback)\b/i,
    value: 18,
  },
  {
    factor: "identityDocument",
    pattern:
      /\b(passport|driver'?s?\s?licen[sc]e|id card|\bssn\b|social security|fake id|date of birth|\bdob\b)\b/i,
    value: 12,
  },
  {
    factor: "controlledSubstance",
    pattern:
      /\b(pure|uncut|aaa\+*|fentanyl|carfentanil|heroin|cocaine|meth(?:amphetamine)?|\bmdma\b|\blsd\b|ketamine|oxycodone|xanax|controlled substances?)\b/i,
    value: 18,
  },
  {
    factor: "weapon",
    pattern:
      /\b(glock|pistol|firearm|handgun|ammo(?:nition)?|silencer|suppressor|ghost gun|untraceable weapon|explosive device)\b/i,
    value: 15,
  },
  {
    factor: "operationalSecurity",
    pattern:
      /\b(burner phone|untraceable|no ?le\b|stealth (?:ship|packaging)|encrypted|\bpgp\b|monero|\bxmr\b|escrow|wipe metadata|\btor\b|\bvpn\b|cash only|no camera|off.?grid|off.?platform|main account|anonymous account|keep (?:this|it) (?:private|secret))\b/i,
    value: 12,
  },
  {
    factor: "urgencyPressure",
    pattern:
      /\b(act now|limited time|don'?t tell anyone|keep this (?:secret|between us)|verify payment now|wire (?:it |the money )?immediately|final warning|last chance|this (?:is )?urgent|urgent(?:ly)?\b.{0,20}\b(response|reply|action)|^urgent\b)\b/i,
    value: 10,
  },
  {
    factor: "transactionCoordination",
    pattern:
      /\b(payment (?:has been |was )?sent|payment confirm(?:ed|ation)|buyer (?:has )?confirmed|awaiting confirmation|package (?:is )?ready|transaction (?:is )?(?:pending|awaiting|complete|confirmed))\b/i,
    value: 15,
  },
];

/**
 * Deterministic suspicion scorer.
 *
 * The LLM has NO influence over this score.
 */
export function computeSuspicionSignals(
  ocrText: string
): SuspicionSignal[] {
  const signals: SuspicionSignal[] = [];

  for (const group of SUSPICION_GROUPS) {
    if (group.pattern.test(ocrText)) {
      signals.push({
        label: SUSPICION_FACTOR_LABELS[group.factor],
        value: group.value,
        factor: group.factor,
      });
    }
  }

  return signals;
}

// ─── LLM Sentiment ──────────────────────────────────────────────────────

export type SentimentLabel = "positive" | "neutral" | "negative";

export interface SentimentSummary {
  label: SentimentLabel;

  /**
   * LLM confidence from 0 to 1.
   */
  confidence: number;

  /**
   * Up to three emotional signals identified by the LLM.
   */
  emotions: string[];

  /**
   * Short linguistic explanation produced by the LLM.
   */
  reasoning: string;

  /**
   * Always "llm" for a successful LLM analysis,
   * "fallback" when the model could not be reached.
   */
  source: "llm" | "fallback";

  /**
   * Model used for sentiment analysis.
   */
  modelUsed: string;
}

export interface OcrTextAnalysis {
  suspicious: boolean;
  suspicionScore: number;
  suspicionLevel: RiskLevel;
  signals: SuspicionSignal[];

  /**
   * LLM-based sentiment result.
   */
  sentiment: SentimentSummary;

  /**
   * Investigator-facing explanation.
   */
  explanation: string;

  /**
   * Whether the explanation was generated by the LLM.
   */
  aiGenerated: boolean;

  /**
   * Model used for the explanation.
   */
  modelUsed: string;
}

interface LlmAnalysisResponse {
  sentiment?: {
    label?: string;
    confidence?: number;
    emotions?: string[];
    reasoning?: string;
  };
  explanation?: string;
}

// ─── Validation helpers ─────────────────────────────────────────────────

function normalizeSentimentLabel(value: unknown): SentimentLabel | null {
  if (typeof value !== "string") return null;

  const normalized = value.toLowerCase().trim();

  if (
    normalized === "positive" ||
    normalized === "neutral" ||
    normalized === "negative"
  ) {
    return normalized;
  }

  return null;
}

function normalizeConfidence(value: unknown): number {
  const numberValue =
    typeof value === "number" ? value : Number(value);

  if (!Number.isFinite(numberValue)) {
    return 0;
  }

  return Math.max(0, Math.min(1, numberValue));
}

function normalizeEmotions(value: unknown): string[] {
  if (!Array.isArray(value)) return [];

  return value
    .filter((emotion): emotion is string => typeof emotion === "string")
    .map((emotion) => emotion.trim())
    .filter(Boolean)
    .slice(0, 3);
}

// ─── Fallback ───────────────────────────────────────────────────────────

function fallbackSentiment(): SentimentSummary {
  return {
    label: "neutral",
    confidence: 0,
    emotions: [],
    reasoning:
      "LLM sentiment analysis was unavailable, so no reliable sentiment classification was produced.",
    source: "fallback",
    modelUsed: "fallback",
  };
}

function templatedExplanation(
  signals: SuspicionSignal[],
  sentiment: SentimentSummary,
  level: RiskLevel
): string {
  if (signals.length === 0) {
    return `No deterministic suspicion indicators matched in the extracted text. LLM sentiment analysis was unavailable.`;
  }

  const factorList = signals
    .map((s) => s.label.toLowerCase())
    .join(", ");

  return (
    `Extracted text matched ${signals.length} indicator group${
      signals.length === 1 ? "" : "s"
    } (${factorList}), putting the suspicion level at ${level}. ` +
    `LLM sentiment analysis was unavailable.`
  );
}

// ─── Main analysis pipeline ─────────────────────────────────────────────

/**
 * Full OCR analysis:
 *
 *   OCR text
 *      ↓
 *   deterministic suspicion scoring
 *      ↓
 *   LLM sentiment + explanation
 *
 * IMPORTANT:
 * The LLM does NOT determine suspicionScore or suspicionLevel.
 */
export async function analyzeOcrText(
  ocrText: string,
  model: SupportedModel = DEFAULT_MODEL
): Promise<OcrTextAnalysis> {
  const cleanText = ocrText.trim();

  // 1. Deterministic suspicion analysis
  const signals = computeSuspicionSignals(cleanText);

  const suspicionScore = Math.min(
    100,
    signals.reduce((sum, signal) => sum + signal.value, 0)
  );

  const suspicionLevel = riskToStatus(suspicionScore);

  const suspicious =
    suspicionLevel === "MEDIUM" ||
    suspicionLevel === "HIGH" ||
    suspicionLevel === "CRITICAL";

  // 2. LLM sentiment + explanation
  try {
    const prompt = [
      "Analyze the emotional sentiment and tone of the following OCR-extracted evidence text.",
      "",
      "Classify the overall sentiment as exactly one of:",
      "- positive",
      "- neutral",
      "- negative",
      "",
      "Also provide:",
      "1. confidence: a number from 0 to 1",
      "2. emotions: up to 3 relevant emotions",
      "3. reasoning: a short explanation of the linguistic/emotional tone",
      "4. explanation: a short investigator-facing explanation",
      "",
      "IMPORTANT:",
      "- Analyze sentiment and emotional tone only.",
      "- Do not decide whether the text is criminal or illegal.",
      "- Do not invent facts.",
      "- Do not change or reinterpret the deterministic suspicion score.",
      "- Do not treat suspicious terminology automatically as negative sentiment.",
      "- Return ONLY valid JSON.",
      "",
      "Expected JSON structure:",
      JSON.stringify(
        {
          sentiment: {
            label: "negative",
            confidence: 0.94,
            emotions: ["fear", "urgency"],
            reasoning:
              "The text uses urgent and threatening language that creates a strongly negative emotional tone.",
          },
          explanation:
            "The extracted text contains language associated with urgency and pressure, resulting in a negative emotional tone.",
        },
        null,
        2
      ),
      "",
      `Deterministic suspicion score: ${suspicionScore}/100`,
      `Deterministic suspicion level: ${suspicionLevel}`,
      "",
      "OCR TEXT:",
      `"""${cleanText.slice(0, 6000)}"""`,
    ].join("\n");

    const parsed = await callLlmForJson<LlmAnalysisResponse>({
      model,
      prompt,
      systemInstruction:
        "You are an AI sentiment-analysis component inside a digital evidence intelligence platform. Analyze linguistic tone objectively. Return only JSON.",
    });

    const label = normalizeSentimentLabel(
      parsed?.sentiment?.label
    );

    if (!label) {
      throw new LlmError(
        "LLM returned an invalid sentiment label"
      );
    }

    const confidence = normalizeConfidence(
      parsed?.sentiment?.confidence
    );

    const emotions = normalizeEmotions(
      parsed?.sentiment?.emotions
    );

    const reasoning =
      typeof parsed?.sentiment?.reasoning === "string" &&
      parsed.sentiment.reasoning.trim()
        ? parsed.sentiment.reasoning.trim()
        : "The LLM did not provide a sentiment reasoning.";

    const explanation =
      typeof parsed?.explanation === "string" &&
      parsed.explanation.trim()
        ? parsed.explanation.trim()
        : reasoning;

    return {
      suspicious,
      suspicionScore,
      suspicionLevel,
      signals,

      sentiment: {
        label,
        confidence,
        emotions,
        reasoning,
        source: "llm",
        modelUsed: model,
      },

      explanation,

      aiGenerated: true,
      modelUsed: model,
    };
  } catch (err) {
    console.error(
      "[ocrSentiment] LLM analysis failed:",
      err instanceof Error ? err.message : err
    );

    const sentiment = fallbackSentiment();

    return {
      suspicious,
      suspicionScore,
      suspicionLevel,
      signals,
      sentiment,
      explanation: templatedExplanation(
        signals,
        sentiment,
        suspicionLevel
      ),
      aiGenerated: false,
      modelUsed: "fallback",
    };
  }
}