import { useState, useEffect } from 'react';
import { apiGet } from '../lib/api';
const rows = [
 ['INF-001','ONION_SERVICE','dw-demo-7xk3.onion','ACT-003','91%','22 Sep 2026'],
 ['INF-002','TLS_CERTIFICATE','SHA256: 4A8E…C91D','ACT-005','84%','21 Sep 2026'],
 ['INF-003','CLEARNET_DOMAIN','demo-clearnet.example','ACT-006','76%','20 Sep 2026'],
 ['INF-004','SERVER_FINGERPRINT','nginx-demo-fp-17','ACT-005','72%','20 Sep 2026'],
 ['INF-005','TOR_DESCRIPTOR','descriptor-demo-04','ACT-001','68%','19 Sep 2026'],
];
export function InfrastructureScreen(){const [items,setItems]=useState<any[][]>(rows); const [sel,setSel]=useState<any[]>(rows[0]); useEffect(()=>{apiGet<any[]>('/api/infrastructure').then(data=>{if(data?.length){const mapped=data.map((r:any)=>[r.displayId,r.type,r.value,r.entity?.displayId??'—',`${r.confidence}%`,new Date(r.lastSeen).toLocaleDateString()]);setItems(mapped);setSel(mapped[0]);}}).catch(()=>{});},[]); return <div style={{padding:'26px 28px'}}><div style={{marginBottom:22}}><h1 className="section-head">Infrastructure Intelligence</h1><p className="page-sub">Passive correlation of hidden-service and clearnet infrastructure indicators using synthetic/authorized records.</p></div><div className="card" style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>Indicator</th><th>Type</th><th>Value</th><th>Actor</th><th>Confidence</th><th>Last Seen</th></tr></thead><tbody>{items.map(r=><tr key={r[0]} onClick={()=>setSel(r)} style={{cursor:'pointer'}}><td className="mono" style={{color:'var(--accent-hi)'}}>{r[0]}</td><td><span className="badge badge-accent">{r[1]}</span></td><td className="mono-sm">{r[2]}</td><td>{r[3]}</td><td><b>{r[4]}</b></td><td>{r[5]}</td></tr>)}</tbody></table></div><div className="card" style={{marginTop:16,padding:18}}><div className="card-title">Correlation path</div><div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap',marginTop:14}}>{['Onion service','TLS certificate','Clearnet domain','Actor candidate'].map((x,i)=><div key={x} style={{display:'flex',alignItems:'center',gap:10}}><div style={{padding:'9px 12px',border:'1px solid var(--border)',borderRadius:7,fontSize:11}}>{x}</div>{i<3&&<span style={{color:'var(--text-4)'}}>→</span>}</div>)}</div><div style={{fontSize:11,color:'var(--text-4)',marginTop:14}}>Selected: {sel[0]} · {sel[2]} · {sel[3]} · confidence {sel[4]}</div></div></div>}
